---
- name: Check if tutor is already installed
  command: which tutor
  register: tutor_check
  ignore_errors: yes
  changed_when: false

- name: Install tutor
  block:
    - name: Install pip3
      apt:
        name: python3-pip
        state: present
        update_cache: yes
      
    - name: Install tutor using pip
      pip:
        name: tutor
        state: present
        executable: pip3
      
    - name: Verify tutor is installed
      command: tutor --version
      register: tutor_version
      
    - name: Display tutor version
      debug:
        msg: "Tutor version: {{ tutor_version.stdout }}"
  when: tutor_check.rc != 0

- name: Create tutor Kubernetes plugin directory
  file:
    path: ~/.local/share/tutor-plugins
    state: directory
    mode: '0755'

- name: Download tutor plugins for K8s
  block:
    - name: Install tutor kubernetes plugin
      pip:
        name: tutor-k8s
        state: present
        executable: pip3
      
    - name: Enable tutor kubernetes plugin
      command: tutor plugins enable k8s
      
    - name: Install tutor minio plugin
      pip:
        name: tutor-minio
        state: present
        executable: pip3
      
    - name: Enable tutor minio plugin
      command: tutor plugins enable minio

- name: Get worker nodes IPs from Ansible inventory
  set_fact:
    worker_nodes_ips: "{{ groups['k3s_node'] | map('extract', hostvars, ['ansible_host']) | list }}"

- name: Configure tutor for OpenEdX
  block:
    - name: Set OpenEdX configuration
      command: "{{ item }}"
      with_items:
        - tutor config save --set LMS_HOST={{ openedx_domain }}
        - tutor config save --set CMS_HOST=studio.{{ openedx_domain }}
        - tutor config save --set ENABLE_HTTPS=true
        - tutor config save --set OPENEDX_COMMON_VERSION=nutmeg
        - tutor config save --set K8S_NAMESPACE=openedx
        - tutor config save --set K8S_INGRESS_ENABLED=true
      register: tutor_config
      changed_when: tutor_config.rc == 0
      
    - name: Set admin credentials
      command: >
        tutor config save --set OPENEDX_COMMON_ACCOUNT_PASSWORD={{ admin_password }}
      register: tutor_credentials
      changed_when: tutor_credentials.rc == 0

- name: Create OpenEdX namespace
  command: kubectl create namespace openedx
  register: create_namespace
  failed_when: create_namespace.rc != 0 and "AlreadyExists" not in create_namespace.stderr

- name: Initialize OpenEdX on Kubernetes
  block:
    - name: Deploy OpenEdX to K3s
      command: tutor k8s start
      register: tutor_deploy
      changed_when: tutor_deploy.rc == 0
      
    - name: Wait for deployments to be ready
      shell: >
        kubectl wait --namespace openedx
        --for=condition=ready pod
        --selector=app.kubernetes.io/instance=openedx
        --timeout=300s
      ignore_errors: yes
      
    - name: Create LoadBalancer service for OpenEdX
      copy:
        content: |
          apiVersion: v1
          kind: Service
          metadata:
            name: tutor-lb
            namespace: openedx
          spec:
            type: LoadBalancer
            ports:
            - name: http
              port: 80
              targetPort: 80
            - name: https
              port: 443
              targetPort: 443
            selector:
              app.kubernetes.io/name: nginx
        dest: /tmp/tutor-lb.yaml
      
    - name: Apply LoadBalancer service
      command: kubectl apply -f /tmp/tutor-lb.yaml
      register: lb_result
      changed_when: lb_result.rc == 0
      
    - name: Wait for LoadBalancer to get an external IP
      shell: kubectl get svc -n openedx tutor-lb -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
      register: lb_ip
      retries: 30
      delay: 10
      until: lb_ip.stdout != ""
      changed_when: false
      
    - name: Display LoadBalancer IP
      debug:
        msg: "OpenEdX is now available at https://{{ openedx_domain }} via IP {{ lb_ip.stdout }}"

- name: Initialize OpenEdX platform
  block:
    - name: Create OpenEdX admin user and database
      command: tutor k8s init
      register: tutor_init
      changed_when: tutor_init.rc == 0
      
    - name: Import demo course
      command: tutor k8s importdemocourse
      register: tutor_demo
      changed_when: tutor_demo.rc == 0
      ignore_errors: yes
