---
# First prepare worker nodes for OpenEdX data storage
- name: Include worker node preparation tasks
  include_tasks: prepare_workers.yml

# Then run all primary node tasks to deploy and configure OpenEdX
- name: Include primary node preparation tasks
  include_tasks: prepare_primary_node.yml
