---
# Example OpenEdX configuration - Copy this file to main.yml and modify as needed

# Domain configuration
openedx_domain: "threefold.pro"  # Replace with your domain

# Platform settings
platform_name: "ThreeFold K3S School"
contact_email: "logismos@protonmail.ch"
language_code: "en"

# Admin user settings
admin_password: "password123"  # Important: Replace with a secure password

# Additional OpenEdX settings
# Uncomment and modify as needed
# theme_name: "custom-theme"
# enable_https: true
