---
- name: Configure Common
  hosts: all
  become: yes
  roles:
    - role: common
      tags: [common]

- name: Configure K3s Control Plane
  hosts: k3s_control
  become: yes
  roles:
    - role: control
      tags: [control]

- name: Join K3s Worker Nodes
  hosts: k3s_node
  become: yes
  roles:
    - role: worker
      tags: [worker]

- name: Deploy OpenEdX with Tutor
  hosts: k3s_control[0]
  become: yes
  roles:
    - role: tutor
      tags: [tutor]
  vars:
    openedx_domain: "{{ openedx_domain | default('onlineschool.com') }}"
    admin_password: "{{ admin_password | default('securepassword') }}"
    worker_public_ips: "{{ groups['k3s_node'] | map('extract', hostvars, ['ansible_host']) | list }}"
